//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ... By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <iostream>
using namespace std;
int main(){
    int multiples = 0;
    int i=1, j=1, temp=0;
    while(i<4000000){
        temp = i + j;
        i = j;
        j = temp;
        if(temp%2==0){
            multiples += temp;
        }
    }
    cout << multiples;
}
